GET https://localhost:7014/api/Auth/me
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1laWRlbnRpZmllciI6IjYyNzAwOGYwLTBhNWMtNGJkMy1iNmI3LWY5YjUzNDA0MzZmNyIsImh0dHA6Ly9zY2hlbWFzLnhtbHNvYXAub3JnL3dzLzIwMDUvMDUvaWRlbnRpdHkvY2xhaW1zL2VtYWlsYWRkcmVzcyI6ImNodW5oYXRsYW0yMDA0QGdtYWlsLmNvbSIsImh0dHA6Ly9zY2hlbWFzLnhtbHNvYXAub3JnL3dzLzIwMDUvMDUvaWRlbnRpdHkvY2xhaW1zL25hbWUiOiJOaOG6rXQgTMOibSIsImh0dHA6Ly9zY2hlbWFzLm1pY3Jvc29mdC5jb20vd3MvMjAwOC8wNi9pZGVudGl0eS9jbGFpbXMvcm9sZSI6IlBhcmVudCIsImp0aSI6ImMzZDRiMWM4LWRjZjYtNDYyZi05ODEyLTU1OTVkMGRiN2ZlMCIsImV4cCI6MTc3OTE5MDExOSwiaXNzIjoiS0lESU8iLCJhdWQiOiJLSURJTy1DbGllbnQifQ.mqFj815jvNDduQoD--5QGD6LVMezGvRUEZh4muCeCyY